In [3]:
from HW2_utils import FKHW2
import numpy as np

q = [0,0,0]
R,P,R_e,p_e = FKHW2(q)

R1 = (R[:,:,0])
R2 = (R[:,:,1])
R3 = (R[:,:,2])
rotateZ = np.array([0,0,1]).reshape(3,1)

angularJ01 = np.matmul(R1,rotateZ)
angularJ02 = np.matmul(R2,rotateZ)
angularJ03 = np.matmul(R3,rotateZ)

angularJacobian = np.concatenate((angularJ01,angularJ02,angularJ03),axis = 1)

# print(R1)
# print("\n")
# print(rotateZ)
# print("\n")
# print(angularJ01)
# print(angularJ02)
# print(angularJ03)
# print("\n")
# print(angularJacobian)
# print("\n")

velocityJ01 = np.cross(angularJ01.reshape(1,3),(p_e-P[:,0])).reshape(3,1)
velocityJ02 = np.cross(angularJ02.reshape(1,3),(p_e-P[:,1])).reshape(3,1)
velocityJ03 = np.cross(angularJ03.reshape(1,3),(p_e-P[:,2])).reshape(3,1)

velocityJacobian = np.concatenate((velocityJ01,velocityJ02,velocityJ03),axis = 1)

an = np.concatenate((angularJacobian,velocityJacobian),axis = 0)

print(angularJacobian)
print("\n")
print(velocityJacobian)
print("\n")
print(np.array([angularJacobian,velocityJacobian]).reshape(6,3))


[[0.00000000e+00 1.22464685e-16 1.22464685e-16]
 [0.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 6.12323426e-17 6.12323426e-17]]


[[-1.09000000e-01 -9.30000000e-02 -9.30000000e-02]
 [ 8.99430000e-01  6.64634217e-17  4.04396760e-17]
 [ 0.00000000e+00 -8.99430000e-01 -4.74430000e-01]]


[[ 0.00000000e+00  1.22464685e-16  1.22464685e-16]
 [ 0.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  6.12323426e-17  6.12323426e-17]
 [-1.09000000e-01 -9.30000000e-02 -9.30000000e-02]
 [ 8.99430000e-01  6.64634217e-17  4.04396760e-17]
 [ 0.00000000e+00 -8.99430000e-01 -4.74430000e-01]]


In [5]:
import numpy as np
print(np.linalg.det([[4,4],[4,4]]))
endJacob = an[3:6,:]
print(endJacob)

0.0
[[-1.09000000e-01 -9.30000000e-02 -9.30000000e-02]
 [ 8.99430000e-01  6.64634217e-17  4.04396760e-17]
 [ 0.00000000e+00 -8.99430000e-01 -4.74430000e-01]]


In [3]:
import numpy as np

test334 = np.array([[[1,2,3,4],[4,3,2,1],[1,1,1,1]],
                    [[2,3,2,3],[2,2,2,2],[3,3,3,3]],
                    [[4,3,4,3],[1,2,1,2],[0,0,0,0]]])

print(test334[:,:,1])
np.shape(test334)

[[2 3 1]
 [3 2 3]
 [3 2 0]]


(3, 3, 4)

In [10]:
from HW2_utils import FKHW2
import numpy as np

q = [0,0,0]
w = [1,1,1,1,1,1]

R, P, R_e, p_e = FKHW2(q)
# R1, R2, R3 = R[:,:,0], R[:,:,1], R[:,:,2]
# P1, P2, P3 = P[:,0], P[:,1], P[:,2]
# rotateZ = np.array([0,0,1]).reshape(3,1)
# angularJ01 = R1 @ rotateZ
# angularJ02 = R2 @ rotateZ
# angularJ03 = R3 @ rotateZ
# angularJacobian = np.concatenate((angularJ01,angularJ02,angularJ03), axis = 1)

wt = np.transpose(w)
N0e = np.matmul(R_e,wt[0:3])
F0e = np.matmul(R_e,wt[3:6])
W0e = np.concatenate((N0e,F0e), axis = 0)

# wtest = R_e @ wt
print(W0e)
# print(wtest)
print(wt)
print(w.T)

[1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1]


AttributeError: 'list' object has no attribute 'T'