In [1]:
import numpy as np
import yaml
import os
import sympy as sp

In [2]:
def QuinticTrajGen(t0, tf, q, v):
    quinticTrajMat = np.array([[1, t0, t0**2, t0**3, t0**4, t0**5],
                                [0, 1, 2*t0, 3*t0**2, 4*t0**3, 5*t0**4],
                                [0, 0, 2, 6*t0, 12*t0**2, 20*t0**3],
                                [1, tf, tf**2, tf**3, tf**4, tf**5],
                                [0, 1, 2*tf, 3*tf**2, 4*tf**3, 5*tf**4],
                                [0, 0, 2, 6*tf, 12*tf**2, 20*tf**3]])
    inputParam = np.array([[q[0]],
                            [v[0]],
                            [0],
                            [q[1]],
                            [v[1]],
                            [0]])
    outputParam = np.linalg.inv(quinticTrajMat) @ inputParam
    return outputParam

def QuinticEval(t, param):
    a_t = param[0] + param[1]*t + param[2]*t**2 + param[3]*t**3 + param[4]*t**4 + param[5]*t**5
    adot_t = param[1] + 2*param[2]*t + 3*param[3]*t**2 + 4*param[4]*t**3 + 5*param[5]*t**4
    return float(a_t), float(adot_t)


In [3]:
test1 = QuinticTrajGen(0, 1, [0, 1], [0, 0])
test1

array([[  0.],
       [  0.],
       [  0.],
       [ 10.],
       [-15.],
       [  6.]])

In [5]:
for time in np.arange(0, 1.1, 0.1):
    print(QuinticEval(time, test1)[0], QuinticEval(time, test1)[1])

print("next")

for time in np.arange(0, 1.1, 0.1):
    test2 = QuinticTrajGen(0, 1, [1, 2], [0, 0])
    print(QuinticEval(time, test2)[0], QuinticEval(time, test2)[1])

0.0 0.0
0.008559999999999988 0.24299999999999963
0.05791999999999992 0.7679999999999988
0.1630799999999998 1.322999999999998
0.3174399999999996 1.7279999999999975
0.49999999999999933 1.8749999999999976
0.6825599999999992 1.727999999999997
0.8369199999999992 1.3229999999999977
0.9420799999999996 0.7679999999999989
0.9914400000000012 0.242999999999995
1.0 3.552713678800501e-15
next
1.0 0.0
1.00856 0.24299999999999963
1.0579199999999997 0.7679999999999988
1.1630799999999997 1.322999999999998
1.3174399999999997 1.7279999999999975
1.4999999999999996 1.8749999999999976
1.6825599999999992 1.727999999999997
1.8369199999999992 1.3229999999999977
1.9420799999999996 0.7679999999999989
1.9914400000000003 0.242999999999995
2.0 3.552713678800501e-15


In [29]:


print(os.path.join(os.path.abspath(''), '../'*2, 'install'))
print(os.path.exists(os.path.join('/home/omzlette/gitROS/FRA333_LAB_HW/LAB4/install/doppelt_control/share/doppelt_control/scripts', '../'*5, 'src', 'lab4_29', 'doppelt_control', 'config')))
print(os.path.exists('../../install/'))

/home/omzlette/gitROS/FRA333_LAB_HW/LAB4/src/doc/../../install
True
True


In [31]:


config = {'Kp': 1, 'Ki': 2}
with open('../lab4_29/doppelt_control/config/tracker_config.yaml', 'w') as f:
    yaml.dump(config, f)

In [4]:
with open('../lab4_29/doppelt_control/config/tracker_config.yaml', 'r') as f:
    config1 = yaml.load(f, Loader=yaml.FullLoader)
    print(config1)

{'Kp': [20, 20, 20], 'Ki': [0, 0, 0]}


In [3]:
via_points = [{'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False},
              {'coords': [0, 0, 0], 'marker': False}]

with open('../lab4_29/doppelt_control/config/via_points.yaml', 'w') as f:
    yaml.dump(via_points, f)

In [4]:
len(via_points)

9

In [4]:
via_points

[{'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False},
 {'coords': [0, 0, 0], 'marker': False}]

In [5]:
with open('../lab4_29/doppelt_control/config/via_points.yaml', 'r') as f:
    via_points = yaml.load(f, Loader=yaml.FullLoader)
via_points[0]['coords']

[0, 0, 0]

In [6]:
print(via_points)

[{'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}, {'coords': [0, 0, 0], 'marker': False}]


In [5]:
pts1 = [0, 0, 0]
pts2 = [2, 3, 4]
test1 = np.sqrt((pts2[0]-pts1[0])**2 + (pts2[1]-pts1[1])**2 + (pts2[2]-pts1[2])**2)
test2 = np.linalg.norm(np.array(pts2)-np.array(pts1))

test1, test2

(5.385164807134504, 5.385164807134504)

In [32]:
current_position = np.array([0.997, 0.997, 0.997])
reference_position = np.array([1, 1, 1])
pos_tolerance = reference_position - current_position

print(np.all(np.abs(current_position - reference_position) < 0.005))

print(np.linalg.norm(pos_tolerance) < 0.005)

True
False


In [34]:
test10 = [0, 1, 2, 3, 4, 5]
test11 = test10[3:6]
test11

[3, 4, 5]

In [46]:
arr = np.array([[2, 2, 2]])
arr2 = np.array([[3, 3, 3]])
list(arr) + list(arr2)

[array([2, 2, 2]), array([3, 3, 3])]

In [47]:
np.cross(arr, arr2)

array([[0, 0, 0]])

In [49]:
np.cross(arr.reshape(1, 3), arr2.reshape(1, 3))

array([[0, 0, 0]])

In [51]:
arr @ arr2.T

array([[18]])

In [157]:
def IK_pos(x, y, z):
    # Calculate the joint angles

    # Define the lengths of the links
    l1 = l3 = 0.15
    le = 0.2

    # Calculate the joint angles q1
    q1 = np.arctan2(y, x)

    # Calculate the joint angles q3
    c3 = ((z-l1)**2 + x**2 + y**2 - l3**2 - le**2)/(2*l3*le)

    s3 = np.sqrt(1-c3**2)
    q3 = np.arctan2(s3, c3)

    # Calculate the joint angles q2
    s2 = (-le*s3)*np.sqrt(x**2 + y**2) + (l3 + le*c3)*(z-l1)
    c2 = (l3 + le*c3)*np.sqrt(x**2 + y**2) + (le*s3)*(z-l1)
    q2 = np.arctan2(s2, c2)

    q = [q1, q2, q3]

    return q

In [158]:
x, y, z = 0, 0, 0.3
q1 = IK_pos(x, y, z)[0]
q2 = IK_pos(x, y, z)[1]
q3 = IK_pos(x, y, z)[2]
r01 = np.array([[np.cos(q1), -np.sin(q1), 0],
                [np.sin(q1),  np.cos(q1), 0],
                [      0,        0,       1]])
r02 = np.array([[np.cos(q1)*np.cos(q2), -np.sin(q2)*np.cos(q1),  np.sin(q1)],
                [np.sin(q1)*np.cos(q2), -np.sin(q1)*np.sin(q2), -np.cos(q1)],
                [        np.sin(q2),          np.cos(q2),           0     ]])

r03 = np.array([[-np.sin(q2)*np.sin(q3)*np.cos(q1) + np.cos(q1)*np.cos(q2)*np.cos(q3), -np.sin(q2)*np.cos(q1)*np.cos(q3) - np.sin(q3)*np.cos(q1)*np.cos(q2),  np.sin(q1)],
                [-np.sin(q1)*np.sin(q2)*np.sin(q3) + np.sin(q1)*np.cos(q2)*np.cos(q3), -np.sin(q1)*np.sin(q2)*np.cos(q3) - np.sin(q1)*np.sin(q3)*np.cos(q2), -np.cos(q1)],
                [                 np.sin(q2)*np.cos(q3) + np.sin(q3)*np.cos(q2),                 -np.sin(q2)*np.sin(q3) + np.cos(q2)*np.cos(q3),                    0   ]])
rotateZ = np.array([0, 0, 1]).reshape(3, 1)

In [159]:
angular_J01 = r01 @ rotateZ
angular_J02 = r02 @ rotateZ
angular_J03 = r03 @ rotateZ

In [160]:
l1 = l3 = 0.15
le = 0.2

p01 = np.array([0, 0, l1]).reshape(3, 1)
p02 = np.array([0, 0, l1]).reshape(3, 1)
p03 = np.array([l3*np.cos(q1)*np.cos(q2), l3*np.sin(q1)*np.cos(q2), l1 + l3*np.sin(q2)]).reshape(3, 1)
p_e = np.array([(l3*np.cos(q2) + le*np.cos(q2 + q3))*np.cos(q1), (l3*np.cos(q2) + le*np.cos(q2 + q3))*np.sin(q1), l1 + l3*np.sin(q2) + le*np.sin(q2 + q3)]).reshape(3, 1)

linear_J01 = np.cross(angular_J01, (p_e - p01), axis=0)
linear_J02 = np.cross(angular_J02, (p_e - p02), axis=0)
linear_J03 = np.cross(angular_J03, (p_e - p03), axis=0)

linear_Jacobian = np.concatenate((linear_J01, linear_J02, linear_J03), axis=1)

In [161]:
linear_J01, linear_J02, linear_J03

(array([[0.00000000e+00],
        [5.55111512e-17],
        [0.00000000e+00]]),
 array([[-1.50000000e-01],
        [ 0.00000000e+00],
        [ 5.55111512e-17]]),
 array([[-0.13333333],
        [-0.        ],
        [-0.1490712 ]]))

In [162]:
print(linear_Jacobian)
print(np.linalg.det(linear_Jacobian))
print(np.linalg.inv(np.matrix(linear_Jacobian)))
print(np.linalg.pinv(linear_Jacobian))

[[ 0.00000000e+00 -1.50000000e-01 -1.33333333e-01]
 [ 5.55111512e-17  0.00000000e+00 -0.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17 -1.49071198e-01]]
-1.241267076623634e-18
[[ 0.00000000e+00  1.80143985e+16  0.00000000e+00]
 [-6.66666667e+00  0.00000000e+00  5.96284794e+00]
 [-2.48253415e-15  0.00000000e+00 -6.70820393e+00]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.66666667e+00  0.00000000e+00  5.96284794e+00]
 [-1.77635684e-15  0.00000000e+00 -6.70820393e+00]]


In [171]:
vx, vy, vz = 0, 0, 4
q_dot = np.linalg.pinv(linear_Jacobian) @ np.array([vx, vy, vz]).reshape(3, 1)

In [172]:
print(q_dot)

[[  0.        ]
 [ 23.85139176]
 [-26.83281573]]


In [74]:
p_e.reshape(3, 1)

array([[0.35],
       [0.  ],
       [0.15]])

In [4]:
t0, tf = sp.Symbol('t_i'), sp.Symbol('t_f')

quinticSP = sp.Matrix([[1, t0, t0**2, t0**3, t0**4, t0**5],
            [0, 1, 2*t0, 3*t0**2, 4*t0**3, 5*t0**4],
            [0, 0, 2, 6*t0, 12*t0**2, 20*t0**3],
            [1, tf, tf**2, tf**3, tf**4, tf**5],
            [0, 1, 2*tf, 3*tf**2, 4*tf**3, 5*tf**4],
            [0, 0, 2, 6*tf, 12*tf**2, 20*tf**3]])

sp.latex(quinticSP)

'\\left[\\begin{matrix}1 & t_{i} & t_{i}^{2} & t_{i}^{3} & t_{i}^{4} & t_{i}^{5}\\\\0 & 1 & 2 t_{i} & 3 t_{i}^{2} & 4 t_{i}^{3} & 5 t_{i}^{4}\\\\0 & 0 & 2 & 6 t_{i} & 12 t_{i}^{2} & 20 t_{i}^{3}\\\\1 & t_{f} & t_{f}^{2} & t_{f}^{3} & t_{f}^{4} & t_{f}^{5}\\\\0 & 1 & 2 t_{f} & 3 t_{f}^{2} & 4 t_{f}^{3} & 5 t_{f}^{4}\\\\0 & 0 & 2 & 6 t_{f} & 12 t_{f}^{2} & 20 t_{f}^{3}\\end{matrix}\\right]'

In [6]:
x, y, z, l1, l3, le = sp.Symbol('x'), sp.Symbol('y'), sp.Symbol('z'), sp.Symbol('l_1'), sp.Symbol('l_3'), sp.Symbol('l_e')

eq1 = ((z-l1)**2 + x**2 + y**2 - l3**2 - le**2)/(2*l3*le)

sp.latex(eq1)

'\\frac{- l_{3}^{2} - l_{e}^{2} + x^{2} + y^{2} + \\left(- l_{1} + z\\right)^{2}}{2 l_{3} l_{e}}'

In [9]:
q1, q2, q3 = sp.Symbol('q_1'), sp.Symbol('q_2'), sp.Symbol('q_3')

r01 = sp.Matrix([[sp.cos(q1), -sp.sin(q1), 0],
                [sp.sin(q1),  sp.cos(q1), 0],
                [      0,        0,       1]])
r02 = sp.Matrix([[sp.cos(q1)*sp.cos(q2), -sp.sin(q2)*sp.cos(q1),  sp.sin(q1)],
                [sp.sin(q1)*sp.cos(q2), -sp.sin(q1)*sp.sin(q2), -sp.cos(q1)],
                [        sp.sin(q2),          sp.cos(q2),           0     ]])

r03 = sp.Matrix([[-sp.sin(q2)*sp.sin(q3)*sp.cos(q1) + sp.cos(q1)*sp.cos(q2)*sp.cos(q3), -sp.sin(q2)*sp.cos(q1)*sp.cos(q3) - sp.sin(q3)*sp.cos(q1)*sp.cos(q2),  sp.sin(q1)],
                [-sp.sin(q1)*sp.sin(q2)*sp.sin(q3) + sp.sin(q1)*sp.cos(q2)*sp.cos(q3), -sp.sin(q1)*sp.sin(q2)*sp.cos(q3) - sp.sin(q1)*sp.sin(q3)*sp.cos(q2), -sp.cos(q1)],
                [                 sp.sin(q2)*sp.cos(q3) + sp.sin(q3)*sp.cos(q2),                 -sp.sin(q2)*sp.sin(q3) + sp.cos(q2)*sp.cos(q3),                    0   ]])

print(sp.latex(r01),'\n\n', sp.latex(r02),'\n\n', sp.latex(r03))

\left[\begin{matrix}\cos{\left(q_{1} \right)} & - \sin{\left(q_{1} \right)} & 0\\\sin{\left(q_{1} \right)} & \cos{\left(q_{1} \right)} & 0\\0 & 0 & 1\end{matrix}\right] 

 \left[\begin{matrix}\cos{\left(q_{1} \right)} \cos{\left(q_{2} \right)} & - \sin{\left(q_{2} \right)} \cos{\left(q_{1} \right)} & \sin{\left(q_{1} \right)}\\\sin{\left(q_{1} \right)} \cos{\left(q_{2} \right)} & - \sin{\left(q_{1} \right)} \sin{\left(q_{2} \right)} & - \cos{\left(q_{1} \right)}\\\sin{\left(q_{2} \right)} & \cos{\left(q_{2} \right)} & 0\end{matrix}\right] 

 \left[\begin{matrix}- \sin{\left(q_{2} \right)} \sin{\left(q_{3} \right)} \cos{\left(q_{1} \right)} + \cos{\left(q_{1} \right)} \cos{\left(q_{2} \right)} \cos{\left(q_{3} \right)} & - \sin{\left(q_{2} \right)} \cos{\left(q_{1} \right)} \cos{\left(q_{3} \right)} - \sin{\left(q_{3} \right)} \cos{\left(q_{1} \right)} \cos{\left(q_{2} \right)} & \sin{\left(q_{1} \right)}\\- \sin{\left(q_{1} \right)} \sin{\left(q_{2} \right)} \sin{\left(q_{3} \right)} +

In [11]:
p03 = sp.Matrix([l3*sp.cos(q1)*sp.cos(q2), l3*sp.sin(q1)*sp.cos(q2), l1 + l3*sp.sin(q2)])
p_e = sp.Matrix([(l3*sp.cos(q2) + le*sp.cos(q2 + q3))*sp.cos(q1), (l3*sp.cos(q2) + le*sp.cos(q2 + q3))*sp.sin(q1), l1 + l3*sp.sin(q2) + le*sp.sin(q2 + q3)])

print(sp.latex(p03),'\n\n', sp.latex(p_e))

\left[\begin{matrix}l_{3} \cos{\left(q_{1} \right)} \cos{\left(q_{2} \right)}\\l_{3} \sin{\left(q_{1} \right)} \cos{\left(q_{2} \right)}\\l_{1} + l_{3} \sin{\left(q_{2} \right)}\end{matrix}\right] 

 \left[\begin{matrix}\left(l_{3} \cos{\left(q_{2} \right)} + l_{e} \cos{\left(q_{2} + q_{3} \right)}\right) \cos{\left(q_{1} \right)}\\\left(l_{3} \cos{\left(q_{2} \right)} + l_{e} \cos{\left(q_{2} + q_{3} \right)}\right) \sin{\left(q_{1} \right)}\\l_{1} + l_{3} \sin{\left(q_{2} \right)} + l_{e} \sin{\left(q_{2} + q_{3} \right)}\end{matrix}\right]
